### ISSUE TITLE
自定义apisixRoute实例后controller创建资源报错

### ISSUE THREAD

**Issue by chestarss** [api7/ingress-controller#16]
定义了Route资源
`apiVersion: apisix.apache.org/v1
kind: ApisixRoute
metadata:
  name: test-route
  namespace: testnamespace
  resourceVersion: '80141484'
spec:
  rules:
    - host: xxx.test-dev.com
      http:
        paths:
          - backend:
              serviceName: xxx
              servicePort: 8080
            path: /
`
controller分别添加route失败，到dashboard查看upstream创建了，重启controller，又创建了service，再重启controller又创建了router

`E0610 09:43:03.761447       1 builder.go:123] add route failed, route: &v1.Route{ID:(*string)(0xc00040b3d0), Group:(*string)(0xc0007c61d0), FullName:(*string)(0xc0007c6250), ResourceVersion:(*string)(0xc0007c61e0), Host:(*string)(0xc0007c61f0), Path:(*string)(0xc0007c6210), Name:(*string)(0xc0007c6220), Methods:[]*string(nil), ServiceId:(*string)(0xc0000cf280), ServiceName:(*string)(0xc0007c6230), UpstreamId:(*string)(nil), UpstreamName:(*string)(0xc0007c6240), Plugins:(*v1.Plugins)(0xc0008d60c0)}, err: status: 201, body: {"node":{"value":{"host":"xxx.test-dev.com","plugins":{},"uri":"\/","service_id":"00000000000000000059","desc":"xxx.test-dev.com\/","priority":0},"createdIndex":76,"key":"\/apisix\/routes\/00000000000000000076","modifiedIndex":76},"action":"create"}`

**Comment by membphis** [comment]
@gxthrj do you have time take a look at this issue?

**Comment by chestarss** [comment]
按我的理解，目前的controller没有感知 apisix中的状态是否和CRD instance中定义的资源一致，感觉像是命令式的发起单次api调用apisix，并没有确保CRD资源在apisix中终态保证，也没有重试机制。

从我的实验效果来看，只能通过强制重启controller触发全量更新来逐渐创建对应的upstream、service和router

**Comment by gxthrj** [comment]
@chestarss  This is a bug from the last pr. 
there is a http status check here https://github.com/api7/seven/blob/master/utils/http.go#L23.
but get code 201 when adding route.
I will fix it today

**Comment by gxthrj** [comment]
> 按我的理解，目前的controller没有感知 apisix中的状态是否和CRD instance中定义的资源一致，感觉像是命令式的发起单次api调用apisix，并没有确保CRD资源在apisix中达到终态，也没有重试机制。
> 
> 从我的实验效果来看，只能通过强制重启controller触发全量更新来逐渐创建对应的upstream、service和router

We did sync between the CRD and apisix, it should be idempotent No matter how many times you run the controller

**Comment by gxthrj** [comment]
If you find any problems, you can reopen this issue

**Comment by aoisososola** [comment]
我在k8s中安装的apisix 2.10.0, 在命令行用 kubectl apply 创建的apisixroute ，在dashboard上不显示，重启
apisix-ingress-controller 服务后dashboard 才加载出来，route规则才开始生效。这是怎么回事，还是这个bug吗
