### ISSUE TITLE
English README for a larger audience

### ISSUE THREAD

**Issue by mtx2d** [api7/ingress-controller#18]
Dear Team, 
I like the project and want to use APISIX as my ingress controller for a personal project. 
Noticed that we only have Chinese readme, which limits the audience to only Chinese readers. 

Would it make sense to have an English version, I can help if we need one.

**Comment by moonming** [comment]
@mtx2d Of course, we should have an English version. That will be great if you can help:)

**Comment by mtx2d** [comment]
PR #19 is submitted :D.  

> @mtx2d Of course, we should have an English version. That will be great if you can help:)

**Comment by mtx2d** [comment]
#19  merged, closing this issue.
