### ISSUE TITLE
Official APISIX Ingress Controller Image

### ISSUE THREAD

**Issue by neillee95** [api7/ingress-controller#21]
In the [sample ingress controller](https://github.com/api7/ingress-controller/blob/e9e69058ee83a04ccf9dd52466d42e56f38cecb5/samples/deploy/deployment/ingress-controller.yaml#L30) doc, I need to modify the APISIX ingress controller image, Is there a built ingress controller image?

 I cloned this repository, and built a image by Dockerfile,
```sh
git clone https://github.com/api7/ingress-controller.git
cd ingress-controller
docker build -t APISIX_INGRESS_CONTROLLER_IMAGE .
```
but the built image is 1.1 G, It's a little big.

**Comment by moonming** [comment]
@gxthrj please take a look.

**Comment by gxthrj** [comment]
ok,I will send a pr to reduce image volume
