### ISSUE TITLE
Some questions about deploying APISIX Ingress Controller

### ISSUE THREAD

**Issue by dayongi** [api7/ingress-controller#23]
问题一：k8s已经部署完成，一个master和一个node，完成部署后，我是直接在master节点上apply samples目录中的yaml文件就可以了吗？还是说需要做一些其他的操作？

问题二：因为我们需要的一个服务鉴权的功能，具体的业务需要自己来写，我理解 APISIX ingress controller是通过调度API的方式进行操作etcd以完成配置同步，真正操作客户端请求的还是APISIX，那可能需要自己开发一个小插件来满足业务需求，请问我理解的是否有误？

问题三：如果需要自己开发业务插件或者服务，那么我应该按照APISIX ingress controller文档中的"SDK"的来部署开发环境而不是"deployment"，如果需要部署开发环境，我需要自己开发一些业务，按照文档的描述，我理解是需要在集群外部署APISIX，这个“集群外”是什么意思？是部署在虚拟机上还是放到docker里面呢？具体的部署位置是在master还是node节点上呢？

**Comment by membphis** [comment]
please use English in public channels, and one issue for one question is a good way.
you should create 3 issues for each question.
