### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by dayongi** [api7/ingress-controller#24]
I can't startup the pod of ingress controller follow the doc: https://github.com/api7/ingress-controller/blob/master/doc/dev/develop.md.

step1: kubectl get pods -n coud
![image](https://user-images.githubusercontent.com/41787764/92355465-deeefc00-f116-11ea-95b6-572c0ffa783e.png)

step2:  kubectl describe pod ingress-controller-8686dfdb76-x7mvg -n cloud
![image](https://user-images.githubusercontent.com/41787764/92355673-4d33be80-f117-11ea-89c9-732c14559318.png)

step3: kubectl logs ingress-controller-8686dfdb76-x7mvg -n cloud
![image](https://user-images.githubusercontent.com/41787764/92355703-6177bb80-f117-11ea-99bf-9efc0a6fa996.png)

others:
All nodes: kubectl get nodes
![image](https://user-images.githubusercontent.com/41787764/92355779-89ffb580-f117-11ea-8516-317002979a46.png)

All pods: kubectl get pods -n kube-system
![image](https://user-images.githubusercontent.com/41787764/92355839-aa2f7480-f117-11ea-9753-470c1c3773ba.png)

**Comment by gxthrj** [comment]
need to specify a `ENV` in configmap
