### ISSUE TITLE
doc: How to deploy it on k8s?

### ISSUE THREAD

**Issue by linsir** [api7/ingress-controller#4]
How to deploy it on k8s?

**Comment by 107192468** [comment]
我也需要一份详细的部署文档

**Comment by moonming** [comment]
@gxthrj please take a look

**Comment by gxthrj** [comment]
here is the doc for k8s
https://github.com/api7/ingress-controller/blob/master/doc/deploy/deploy.md

**Comment by gxthrj** [comment]
this issue will be closed
